project_id = "clinic-booking"

[api]
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 15

[auth]
site_url = "http://localhost:3000"
# FR-06: no public sign-up; the single staff account is created by the developer.
enable_signup = false
minimum_password_length = 12
password_requirements = "lower_upper_letters_digits"

[auth.email]
enable_signup = false
enable_confirmations = false
